version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
  - source: /scripts/nominal-api.service
    destination: /lib/systemd/system/
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3600
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3600
      runas: root